### PR TITLE
Move App to Heroku

### PR DESCRIPTION
**Pull request by jamesarosen**
- [x] create a Heroku application
- [x] tell Herkou about domain: `heroku domains:add ahab.io`
- [x] enable PG on Heroku: `heroku addons:add heroku-postgresql`
- [x] add Honeybadger API token to Heroku env: `heroku config:set HONEYBADGER_API_KEY=...`
- [x] export DB from MySQL on Linode
- [x] import DB to PostgreSQL on Heroku: `heroku pgbackups:restore DATABASE 'http://ahab.io/pgdump.txt' --confirm ahabio` (file subsequently removed)
- [x] set `$stdout.sync = true`
- [x] change `config/database.yml` and `Gemfile` to use PostgreSQL
- [x] use `img` helper for `search_glass2x.png` so it uses the right URL in production
- [x] use a Heroku-compatible asset system
- [x] add @svizzari as collaborator on the Heroku app
- [x] CNAME ahab.io to ahabio.herokuapp.com (after merge)

### CODE REVIEW

**Comment by jamesarosen** [comment]
We may end up having to go with AssetPack or Sprockets to get the assets working on Heroku. We can't run `rake assets:compile` there. We're using Fastly for `assets.ahabio.com`, so we could just have Sinatra endpoints for the various assets; they won't get hit very often.

One thing I haven't figured out is how to expire assets on Fastly. Currently we do that in Capistrano's `deploy.rb`, but that isn't run on Heroku.

Heroku's deploy hooks _could_ work, but they're not a great fit. We can't programmatically choose which endpoints to hit in Fastly's expiry API, so we'd have to use the "expire-everything" endpoint, which sucks. We could use [Fastly's surrogate-key feature](https://fastly.zendesk.com/entries/21921227-How-can-I-purge-content-on-Fastly-) and tag all assets with an "asset" tag and have Heroku expire all assets via Fastly's HTTP API.

/cc @svizzari

**Comment by jamesarosen** [comment]
Sadly, Heroku's HTTP post-deploy hook uses a `POST` and Fastly's expiry API expects a `PURGE`. I tried sending a `POST` with `_method=PURGE` to no avail.

**Comment by jamesarosen** [comment]
Though currently we don't set `Cache-Control` headers, even on `assets.ahab.io`. We rely on just `ETag` and `Last-Modified` and have Fastly's servers check for updates on every request.

**Comment by svizzari** [comment]
It looks like we can run assets:precompile though, was documented a few
days ago here https://devcenter.heroku.com/articles/rails-asset-pipeline

On Sunday, October 27, 2013, James Alexander Rosen wrote:

> We may end up having to go with AssetPack or Sprockets to get the assets
> working on Heroku. We can't run rake assets:compile there. We're using
> Fastly for assets.ahabio.com, so we could just have Sinatra endpoints for
> the various assets; they won't get hit very often.
> 
> One thing I haven't figured out is how to expire assets on Fastly.
> Currently we do that in Capistrano's deploy.rb, but that isn't run on
> Heroku.
> 
> Heroku's deploy hooks _could_ work, but they're not a great fit. We can't
> programmatically choose which endpoints to hit in Fastly's expiry API, so
> we'd have to use the "expire-everything" endpoint, which sucks. We could
> use Fastly's tagging feature and tag all assets with an "asset" tag and
> have Heroku expire all assets via Fastly's HTTP API.
> 
> /cc @svizzari https://github.com/svizzari
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/railsrumble/r13-team-352/pull/43#issuecomment-27152056
> .

## 

 Stefan Vizzari
Snr. Software Engineer - APAC

Zendesk http://www.zendesk.com/
Twitter: @s_vizzari  |  Skype: zendesk.svizzari | Phone: +61 407 511 960

**Comment by jamesarosen** [comment]
Yeah. I'll start there. The problem I think I was facing is that the destination directory (`public/`) isn't checked in to source control, so `rake assets:precompile` needs to make it. That's quite easy.

**Comment by svizzari** [comment]
We _want_ precompilation, right. Less work for us, less work for the server :)

**Comment by svizzari** [comment]
Another option might be to use a service like Beanstalk, I have an account
there and they promote their tight integration with heroku

On Sunday, October 27, 2013, James Alexander Rosen wrote:

> Yeah. I'll start there. The problem I think I was facing is that the
> destination directory (public/) isn't checked in to source control, so rake
> assets:precompile needs to make it. That's quite easy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/railsrumble/r13-team-352/pull/43#issuecomment-27158667
> .

## 

 Stefan Vizzari
Snr. Software Engineer - APAC

Zendesk http://www.zendesk.com/
Twitter: @s_vizzari  |  Skype: zendesk.svizzari | Phone: +61 407 511 960

**Comment by jamesarosen** [comment]
I aliased `assets:compile` to `assets:precompile` and pushed to Heroku, but it didn't run the task. I can't figure out why. The [buildpack's check](https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L671) passes for me locally.

I can, however, run `heroku run rake assets:precompile` successfully.

**Comment by svizzari** [comment]
Hmm, perhaps reach out to heroku?  I'll give you access to my beanstalk acct. today, for comparison

**Comment by jamesarosen** [comment]
On deploy, Heroku tells me

```
-----> Writing config/database.yml to read from DATABASE_URL
-----> Discovering process types
       Procfile declares types     -> web
       Default types for Ruby/Rack -> console, rake

-----> Compiled slug size: 25.8MB
-----> Launching... done, v10
       http://ahabio.herokuapp.com deployed to Heroku
```

That suggests that I might be able to declare a `rake` process in the `Procfile`. I tried

```
rake: bundle exec assets:precompile
```

but that didn't change anything (other than make the `rake` type explicit):

```
-----> Writing config/database.yml to read from DATABASE_URL
-----> Discovering process types
       Procfile declares types     -> rake, web
       Default types for Ruby/Rack -> console

-----> Compiled slug size: 25.8MB
-----> Launching... done, v11
       http://ahabio.herokuapp.com deployed to Heroku
```

**Comment by jamesarosen** [comment]
I tried emulating the [check that the buildpack does](https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L671) for the `assets:precompile` task:

```
heroku run "env path=/app/vendor/bundle/ruby/1.9.1/bin:/app/bin:/app/vendor/bundle/bin:/usr/local/bin:/usr/bin:/bin bundle exec rake assets:precompile; echo $?"
Running `env path=/app/vendor/bundle/ruby/1.9.1/bin:/app/bin:/app/vendor/bundle/bin:/usr/local/bin:/usr/bin:/bin bundle exec rake assets:precompile; echo 127` attached to terminal... up, run.2543
Fetched vendor/assets/jquery-ui.css
...
Wrote public/moby_blue2x.png
Wrote public/application.js
"vendor/assets/960_12_col.css" "vendor/assets/jquery-ui.css"
cat "vendor/assets/960_12_col.css" "vendor/assets/jquery-ui.css" > public/vendor.css
"vendor/assets/jquery.min.js" "vendor/assets/handlebars.min.js" "vendor/assets/jquery-ui.min.js"
cat "vendor/assets/jquery.min.js" "vendor/assets/handlebars.min.js" "vendor/assets/jquery-ui.min.js" > public/vendor.js
"vendor/assets/jquery.min.map"
cat "vendor/assets/jquery.min.map" > public/jquery.min.map
Wrote public/application.css
127
```

I can't tell why that exit status is 127. The task worked perfectly.

**Comment by svizzari** [comment]
Hmm, it's like a PID or something?  There is a reference to 127 at the beginning of the log, you saw that?  The value replaces a token, right `echo $?`

**Comment by jamesarosen** [comment]
Oh, I see. My bash is turning `$?` into 127 locally, then sending that value. Good catch. `$?` is the exit code of the last command.

**Comment by jamesarosen** [comment]
Using single-quotes fixes the `$?` problem:

```
heroku run 'env path=$PATH bundle exec rake assets:precompile --dry-run; echo $?'
Running `env path=$PATH bundle exec rake assets:precompile --dry-run; echo $?` attached to terminal... up, run.6474
** Invoke assets:precompile (first_time)
** Invoke assets:compile (first_time)
...
** Execute (dry run) assets:precompile
0
```

But if that command is returning an exit status of `0`, why doesn't the buildpack see it?

**Comment by jamesarosen** [comment]
I opened ticket 101826 with @Heroku.

**Comment by jamesarosen** [comment]
Closed in fbbcf3ee0227a4545ec7fdb5a5dcda31557b414d.

The `assets:precompile` problem was because `Rakefile` required `ahab_application`, which tried to load `ActiveRecord`, but Heroku doesn't configure the database connection by the time it tries to run `assets:precompile`.

**Pull request closed without merging**
